# This is a basic workflow to help you get started with Actions

name: DockerHub_Deployment_CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Run a multi-line script
        run: |
          docker build . -t javeedcts1/docker-hostname-webapp:latest
          docker push javeedcts1/docker-hostname-webapp:latest
